using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Sql;
using System.Data.SqlClient;

namespace BarkodluEnvanterKayit
{
    public partial class kasa : Form
    {
        public kasa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        SqlConnection baglanti = new SqlConnection("Data Source=DESKTOP-BCV2AJ1;Initial Catalog=BarkodEnvanterDB;Integrated Security=True");

        private void btn_kasaKaydet_Click(object sender, EventArgs e)
        {
            //Sql konutlarıyla veritabanına veriler kaydeiliyor
            SqlCommand komut = new SqlCommand("INSERT INTO tblkasa(kasamarka,kasamodel,kasahdd,kasaram,kasagenel,kasadepartman,kasakullanici,kasabarkod) values (@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8) ", baglanti);

            //Textboxlarda yazılanlar parametrelere atanıp veritabanına kaydediliyor
            komut.Parameters.AddWithValue("@p1", Convert.ToString(txt_kasamarka.Text));
            komut.Parameters.AddWithValue("@p2", Convert.ToString(txt_kasamodel.Text));
            komut.Parameters.AddWithValue("@p3", Convert.ToString(txt_kasahdd.Text));
            komut.Parameters.AddWithValue("@p4", Convert.ToString(txt_kasaram.Text));
            komut.Parameters.AddWithValue("@p5", Convert.ToString(txt_kasagenel.Text));
            komut.Parameters.AddWithValue("@p6", Convert.ToString(txt_kasadepartman.Text));
            komut.Parameters.AddWithValue("@p7", Convert.ToString(txt_kasakullanici.Text));
            komut.Parameters.AddWithValue("@p8", Convert.ToString(txt_kasabarkod.Text));

            try//komutları çalıştırmayı dene
            {
                baglanti.Open();
                komut.ExecuteNonQuery();
                MessageBox.Show("Bilgiler Veritabanına Kaydedildi.", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            catch(Exception ex)//Eger hata varsa hata mesajını göster 
            {
                MessageBox.Show(ex.Message.ToString());
            }
            baglanti.Close();
        }

        private void btn_KasaVeriCek_Click(object sender, EventArgs e)
        {
            SqlCommand komut2 = new SqlCommand("SELECT * FROM tblkasa where kasaid=@kasaid", baglanti);//kasaid paramatresindeki degere göre verileri getir
            baglanti.Open();
            komut2.Parameters.AddWithValue("@kasaid", txt_KasaId.Text);//txt kasa id den veri 
            komut2.ExecuteNonQuery();
            SqlDataReader dr = komut2.ExecuteReader();//veri okuma işlemini başlat
            if (dr.Read())//okuma işlemini yap ve tablolardaki verileri sırayla textboxlara aktar
            {
                txt_kasamarka.Text = dr["kasamarka"].ToString();
                txt_kasamodel.Text = dr["kasamodel"].ToString();
                txt_kasahdd.Text = dr["kasahdd"].ToString();
                txt_kasaram.Text = dr["kasaram"].ToString();
                txt_kasagenel.Text = dr["kasagenel"].ToString();
                txt_kasadepartman.Text = dr["kasadepartman"].ToString();
                txt_kasakullanici.Text = dr["kasakullanici"].ToString();
                txt_kasabarkod.Text = dr["kasabarkod"].ToString();
            }
            else // okuma işleminde hata olursa textboxlara bunları yazdır
            {
                txt_kasamarka.Text = "Veri Çekilemedi";
                txt_kasamodel.Text = "Veri Çekilemedi";
                txt_kasahdd.Text = "Veri Çekilemedi";
                txt_kasaram.Text = "Veri Çekilemedi";
                txt_kasagenel.Text = "Veri Çekilemedi";
                txt_kasadepartman.Text = "Veri Çekilemedi";
                txt_kasakullanici.Text = "Veri Çekilemedi";
                txt_kasabarkod.Text = "Veri Çekilemedi";
            }
            baglanti.Close();
        }

        private void btn_TabloYenile_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut3 = new SqlCommand("SELECT * FROM tblkasa", baglanti);//sorgu yazıldı
            SqlDataAdapter da = new SqlDataAdapter(komut3);
            DataTable dt = new DataTable();
            da.Fill(dt);//veriler degiskenlere çekilip doldurma işlemi yapıldı
            gridControl1.DataSource = dt; //datagrid e veriler dolduruldu
            baglanti.Close();
        }

        private void btn_KasaVeriSil_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut4 = new SqlCommand("DELETE FROM tblkasa WHERE kasaid=@kasaid", baglanti); // sql sorgu yazıldı
            komut4.Parameters.AddWithValue("kasaid", txt_KasaId.Text); // kasa id textboxtan çekildi
            komut4.ExecuteNonQuery(); // komut çalıştırıldı
            SqlDataReader dr = komut4.ExecuteReader();
            MessageBox.Show("Veri Silme İşlemi Başarılı !!","Uyarı",MessageBoxButtons.OK,MessageBoxIcon.Warning );
            baglanti.Close();
            txt_KasaId.Text = "";
        }

        private void btn_KasaVeriGuncelle_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut5 = new SqlCommand("UPDATE tblkasa SET kasadepartman=@kasadepartman,kasakullanici=@kasakullanici,kasabarkod=@kasabarkod WHERE kasaid=@kasaid", baglanti);

            komut5.Parameters.AddWithValue("@kasaid", txt_KasaId.Text);
            komut5.Parameters.AddWithValue("@kasadepartman", txt_kasadepartman.Text);
            komut5.Parameters.AddWithValue("@kasakullanici", txt_kasakullanici.Text);
            komut5.Parameters.AddWithValue("@kasabarkod", txt_kasabarkod.Text);

            MessageBox.Show("Güncelleme Başarıyla Tamamlandı.");
            komut5.ExecuteNonQuery();
            baglanti.Close();


        }

        private void btn_FormYenile_Click(object sender, EventArgs e)
        {
            txt_kasamarka.Text = " ";
            txt_kasamodel.Text = " ";
            txt_kasahdd.Text = " ";
            txt_kasaram.Text = " ";
            txt_kasagenel.Text = " ";
            txt_kasadepartman.Text = " ";
            txt_kasakullanici.Text = " ";
            txt_kasabarkod.Text = " ";
            txt_KasaId.Text = "";
        }

        private void Btn_KasExcell_Click(object sender, EventArgs e)
        {
            SaveFileDialog sfd = new SaveFileDialog();
            sfd.Filter = ".xls (*.xls)|*.xls"; //xls dosyası oluştur
            sfd.FileName = "KasaVeriler.xls"; //dosya adı belirlendi
            DialogResult res = sfd.ShowDialog();
            if (res == DialogResult.OK)
            {
                gridView1.ExportToXls(sfd.FileName);//tablodaki veriler komple export et
            }
        }
    }
}
