using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Sql;
using System.Data.SqlClient;

namespace BarkodluEnvanterKayit
{
    public partial class yazici : Form
    {
        public yazici()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        SqlConnection baglanti = new SqlConnection("Data Source=DESKTOP-BCV2AJ1;Initial Catalog=BarkodEnvanterDB;Integrated Security=True");
        private void Btn_EkranKaydet_Click(object sender, EventArgs e)
        {
            //Sql konutlarıyla veritabanına veriler kaydediliyor
            SqlCommand komut = new SqlCommand("INSERT INTO tblyazici(yazicimarka,yazicimodel,yazicidepartman,yazicikullanici,yazicibarkod) values (@p1,@p2,@p3,@p4,@p5) ", baglanti);

            //Textboxlarda yazılanlar parametrelere atanıp veritabanına kaydediliyor
            komut.Parameters.AddWithValue("@p1", Convert.ToString(txt_YaziciMarka.Text));
            komut.Parameters.AddWithValue("@p2", Convert.ToString(txt_YaziciModel.Text));
            komut.Parameters.AddWithValue("@p3", Convert.ToString(txt_YaziciDepartman.Text));
            komut.Parameters.AddWithValue("@p4", Convert.ToString(txt_YaziciKullanici.Text));
            komut.Parameters.AddWithValue("@p5", Convert.ToString(txt_YaziciBarkod.Text));


            try//komutları çalıştırmayı dene
            {
                baglanti.Open();
                komut.ExecuteNonQuery();
                MessageBox.Show("Bilgiler Veritabanına Kaydedildi.", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

            catch (Exception ex)//Eger hata varsa hata mesajını göster 
            {
                MessageBox.Show(ex.Message.ToString());
            }
            baglanti.Close();
        }

        private void Btn_YaziciVeriCek_Click(object sender, EventArgs e)
        {
            SqlCommand komut2 = new SqlCommand("SELECT * FROM tblyazici where yaziciid=@yaziciid", baglanti);//yaziciid paramatresindeki degere göre verileri getir
            baglanti.Open();
            komut2.Parameters.AddWithValue("@yaziciid", txt_Yaziciid.Text);//txt yaziciid de yazan veri alınıyor
            komut2.ExecuteNonQuery();
            SqlDataReader dr = komut2.ExecuteReader();//veri okuma işlemini başlat
            if (dr.Read())//okuma işlemini yap ve tablolardaki verileri sırayla textboxlara aktar
            {
                txt_YaziciMarka.Text = dr["yazicimarka"].ToString();
                txt_YaziciModel.Text = dr["yazicimodel"].ToString();
                txt_YaziciDepartman.Text = dr["yazicidepartman"].ToString();
                txt_YaziciKullanici.Text = dr["yazicikullanici"].ToString();
                txt_YaziciBarkod.Text = dr["yazicibarkod"].ToString();

            }
            else // okuma işleminde hata olursa textboxlara bunları yazdır
            {
                txt_YaziciMarka.Text = "Veri Çekilemedi";
                txt_YaziciModel.Text = "Veri Çekilemedi";
                txt_YaziciDepartman.Text = "Veri Çekilemedi";
                txt_YaziciKullanici.Text = "Veri Çekilemedi";
                txt_YaziciBarkod.Text = "Veri Çekilemedi";

            }
            baglanti.Close();
        }

        private void btn_YaziciVeriGuncelle_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut5 = new SqlCommand("UPDATE tblyazici SET yazicidepartman=@yazicidepartman,yazicikullanici=@yazicikullanici,yazicibarkod=@yazicibarkod WHERE yaziciid=@yaziciid", baglanti);

            komut5.Parameters.AddWithValue("@yaziciid", txt_Yaziciid.Text);
            komut5.Parameters.AddWithValue("@yazicidepartman", txt_YaziciDepartman.Text);
            komut5.Parameters.AddWithValue("@yazicikullanici", txt_YaziciKullanici.Text);
            komut5.Parameters.AddWithValue("@yazicibarkod", txt_YaziciBarkod.Text);

            MessageBox.Show("Güncelleme Başarıyla Tamamlandı.");
            komut5.ExecuteNonQuery();
            baglanti.Close();
        }

        private void Btn_YaziciVeriSil_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut4 = new SqlCommand("DELETE FROM tblyazici WHERE yaziciid=@yaziciid", baglanti); // sql sorgu yazıldı
            komut4.Parameters.AddWithValue("yaziciid", txt_Yaziciid.Text); // kasa id textboxtan çekildi
            komut4.ExecuteNonQuery(); // komut çalıştırıldı
            SqlDataReader dr = komut4.ExecuteReader();
            MessageBox.Show("Veri Silme İşlemi Başarılı !!", "Uyarı", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            baglanti.Close();
            txt_Yaziciid.Text = "";
        }

        private void btn_FormYenile_Click(object sender, EventArgs e)
        {
            txt_YaziciMarka.Text = " ";
            txt_YaziciModel.Text = " ";
            txt_YaziciDepartman.Text = " ";
            txt_YaziciKullanici.Text = " ";
            txt_YaziciBarkod.Text = " ";
            txt_Yaziciid.Text = " ";
        }

        private void btn_TabloYenile_Click(object sender, EventArgs e)
        {
            baglanti.Open();
            SqlCommand komut3 = new SqlCommand("SELECT * FROM tblyazici", baglanti);//sorgu yazıldı
            SqlDataAdapter da = new SqlDataAdapter(komut3);
            DataTable dt = new DataTable();
            da.Fill(dt);//veriler degiskenlere çekilip doldurma işlemi yapıldı
            gridC_Yazici.DataSource = dt; //datagrid e veriler dolduruldu
            baglanti.Close();
        }

        private void btn_YaziciExcell_Click(object sender, EventArgs e)
        {
            SaveFileDialog sfd = new SaveFileDialog();
            sfd.Filter = ".xls (*.xls)|*.xls"; //xls dosyası oluştur
            sfd.FileName = "YaziciVeriler.xls"; //dosya adı belirlendi
            DialogResult res = sfd.ShowDialog();
            if (res == DialogResult.OK)
            {
                gridC_Yazici.ExportToXls(sfd.FileName);//tablodaki veriler komple export et
            }
        }
    }
}
